/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingListsRouteImport } from './routes/shopping-lists'
import { Route as MealPlansRouteImport } from './routes/meal-plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MealsIndexRouteImport } from './routes/meals.index'
import { Route as MealsNewRouteImport } from './routes/meals.new'
import { Route as MealsMealIdRouteImport } from './routes/meals.$mealId'
import { Route as MealsMealIdEditRouteImport } from './routes/meals.$mealId.edit'

const ShoppingListsRoute = ShoppingListsRouteImport.update({
  id: '/shopping-lists',
  path: '/shopping-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlansRoute = MealPlansRouteImport.update({
  id: '/meal-plans',
  path: '/meal-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsIndexRoute = MealsIndexRouteImport.update({
  id: '/meals/',
  path: '/meals/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsNewRoute = MealsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MealsRoute,
} as any)
const MealsMealIdRoute = MealsMealIdRouteImport.update({
  id: '/meals/$mealId',
  path: '/meals/$mealId',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsMealIdEditRoute = MealsMealIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MealsMealIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/login': typeof LoginRoute
  '/meal-plans': typeof MealPlansRoute
  '/shopping-lists': typeof ShoppingListsRoute
  '/meals/$mealId': typeof MealsMealIdRouteWithChildren
  '/meals/new': typeof MealsNewRoute
  '/meals/': typeof MealsIndexRoute
  '/meals/$mealId/edit': typeof MealsMealIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/login': typeof LoginRoute
  '/meal-plans': typeof MealPlansRoute
  '/shopping-lists': typeof ShoppingListsRoute
  '/meals/$mealId': typeof MealsMealIdRouteWithChildren
  '/meals/new': typeof MealsNewRoute
  '/meals': typeof MealsIndexRoute
  '/meals/$mealId/edit': typeof MealsMealIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/login': typeof LoginRoute
  '/meal-plans': typeof MealPlansRoute
  '/shopping-lists': typeof ShoppingListsRoute
  '/meals/$mealId': typeof MealsMealIdRouteWithChildren
  '/meals/new': typeof MealsNewRoute
  '/meals/': typeof MealsIndexRoute
  '/meals/$mealId/edit': typeof MealsMealIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/login'
    | '/meal-plans'
    | '/shopping-lists'
    | '/meals/$mealId'
    | '/meals/new'
    | '/meals/'
    | '/meals/$mealId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/login'
    | '/meal-plans'
    | '/shopping-lists'
    | '/meals/$mealId'
    | '/meals/new'
    | '/meals'
    | '/meals/$mealId/edit'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/login'
    | '/meal-plans'
    | '/shopping-lists'
    | '/meals/$mealId'
    | '/meals/new'
    | '/meals/'
    | '/meals/$mealId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRoute
  LoginRoute: typeof LoginRoute
  MealPlansRoute: typeof MealPlansRoute
  ShoppingListsRoute: typeof ShoppingListsRoute
  MealsMealIdRoute: typeof MealsMealIdRouteWithChildren
  MealsIndexRoute: typeof MealsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping-lists': {
      id: '/shopping-lists'
      path: '/shopping-lists'
      fullPath: '/shopping-lists'
      preLoaderRoute: typeof ShoppingListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plans': {
      id: '/meal-plans'
      path: '/meal-plans'
      fullPath: '/meal-plans'
      preLoaderRoute: typeof MealPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/': {
      id: '/meals/'
      path: '/meals'
      fullPath: '/meals/'
      preLoaderRoute: typeof MealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/new': {
      id: '/meals/new'
      path: '/new'
      fullPath: '/meals/new'
      preLoaderRoute: typeof MealsNewRouteImport
      parentRoute: typeof MealsRoute
    }
    '/meals/$mealId': {
      id: '/meals/$mealId'
      path: '/meals/$mealId'
      fullPath: '/meals/$mealId'
      preLoaderRoute: typeof MealsMealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/$mealId/edit': {
      id: '/meals/$mealId/edit'
      path: '/edit'
      fullPath: '/meals/$mealId/edit'
      preLoaderRoute: typeof MealsMealIdEditRouteImport
      parentRoute: typeof MealsMealIdRoute
    }
  }
}

interface MealsMealIdRouteChildren {
  MealsMealIdEditRoute: typeof MealsMealIdEditRoute
}

const MealsMealIdRouteChildren: MealsMealIdRouteChildren = {
  MealsMealIdEditRoute: MealsMealIdEditRoute,
}

const MealsMealIdRouteWithChildren = MealsMealIdRoute._addFileChildren(
  MealsMealIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRoute,
  LoginRoute: LoginRoute,
  MealPlansRoute: MealPlansRoute,
  ShoppingListsRoute: ShoppingListsRoute,
  MealsMealIdRoute: MealsMealIdRouteWithChildren,
  MealsIndexRoute: MealsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
